[add]
usage = "add|a"
help = """
Adds the currently selected files to the database.
This will move the selected files from their current location to DB_DIR/dots.
Afterwards, a symlink will be created at the old location, leading to the now
moved files.
"""
ask = """
Add selected files?
This will move those files from their location into your
DB_DIR and create symlinks on the old location (Y/n) """


[cd]
usage = "cd <ID|..>"
help = """
Changes the working directory to the directory indicated by ID in the current view.
If '..' is given as parameter instead, changes working directory to parent directory.
Note: You can only select files in one view, when changing the directory, the
selection will be reset.
"""


[cleanup]
usage = "cleanup"
help = """
Cleans database and files in DB_DIR/dots.
This will remove all entries from your database without a corresponding file
in DB_DIR/dots.
This will also move all files in DB_DIR/dots without a corresponding entry in
the database to DB_DIR/remove
"""
ask = """
***CAUTION***
This will remove all files from your JSON database with no existing source.
Also, all files from your DB_DIR with no entry in your JSON database will be
moved to DB_DIR/remove/. Continue? (Y/n) """


[delete]
usage = "delete|remove|d|r [trash]"
help = """
Removes all currently selected entries from the database.
Corresponding files in DB_DIR will be moved back to their original location.
If you'd like to move the files to DB_DIR/remove instead, use parameter 'trash'.
"""
ask = """
Delete selected files?
This will remove all selected files from your JSON-database and
move them from your DB_DIR back to their original location. Use command 'd trash'
if you wish to move the files from your DB_DIR to DB_DIR/remove/ instead of
their original location (Y/n) """


[edit]
usage = "edit|e [user|u [<new_name>]]"
help = """
Edits all currently selected entries according to parameters:
user [<new_name>]:
  Update home-directory for all paths, either to <new_name> or - if parameter
  if omitted - to current users home-directory
"""


[list]
usage = "list|l"
help = """
Displays files registered in the database. This enables you to edit, delete or
setup selected files in the database.
"""


[setup]
usage = "create|setup|c|s"
help = """
Inserts symlinks to selected files into your system at exaclty the paths displayed.
This means, if you have another home-directory than the selected files, a new home
directory according to the file-paths will be created. Use the 'edit user' command,
to change the home-directories to your own directory.
"""
ask = """
Start Setup?
This will create new symlinks on your system at *exaclty* the paths of the
selected files. If you'd like to change e.g. the home directory, use 'edit'
command. Proceed with setup? (Y/n) """

