# Default Values

Directory = [105,  -1]
Selected  = [ -1,  34]
Warning   = [124,  -1]
Note      = [220,  -1]
Help      = [ -1, 240]
Accent	  = [105, 240]
PreSelect = [ -1,  34]
NormalMod = [ -1, 240]
VisualMod = [ -1, 124]
FilterMod = [ -1,  34]
